-- SQLite evaluates RLS at the API layer. Membership subqueries are supported in
-- USING clauses and UPDATE checks, but not in INSERT WITH CHECK. Every insert
-- therefore binds the authenticated creator/owner plus a status or role
-- attestation backed by a composite foreign key to workspace_members.

alter table public.workspaces enable row level security;
create policy workspaces_select on public.workspaces for select to authenticated
using (owner_id = auth.uid() or exists (select 1 from workspace_members where workspace_members.workspace_id = workspaces.id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy workspaces_insert on public.workspaces for insert to authenticated
with check (owner_id = auth.uid() and created_by = auth.uid());
create policy workspaces_update on public.workspaces for update to authenticated
using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy workspaces_delete on public.workspaces for delete to authenticated using (owner_id = auth.uid());

alter table public.profiles enable row level security;
create policy profiles_select on public.profiles for select to authenticated using (
  id = auth.uid() or exists (
    select 1 from workspace_members
    where workspace_members.user_id = profiles.id
      and workspace_members.status = 'active'
      and workspace_members.workspace_id in (
        select workspace_id from workspace_members
        where workspace_members.user_id = auth.uid()
          and workspace_members.status = 'active'
      )
  )
);
create policy profiles_insert on public.profiles for insert to authenticated with check (id = auth.uid());
create policy profiles_update on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy profiles_delete on public.profiles for delete to authenticated using (id = auth.uid());

alter table public.workspace_members enable row level security;
create policy workspace_members_select on public.workspace_members for select to authenticated
using (user_id = auth.uid() or exists (select 1 from workspaces where workspaces.id = workspace_members.workspace_id and workspaces.owner_id = auth.uid()));
create policy workspace_members_insert on public.workspace_members for insert to authenticated
with check (workspace_owner_id = auth.uid() and created_by = auth.uid());
create policy workspace_members_update on public.workspace_members for update to authenticated
using (workspace_owner_id = auth.uid())
with check (workspace_owner_id = auth.uid());
create policy workspace_members_delete on public.workspace_members for delete to authenticated
using (workspace_owner_id = auth.uid());

alter table public.teams enable row level security;
create policy teams_select on public.teams for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = teams.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy teams_insert on public.teams for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy teams_update on public.teams for update to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = teams.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check (exists (select 1 from workspace_members where workspace_members.workspace_id = teams.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy teams_delete on public.teams for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = teams.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

alter table public.team_memberships enable row level security;
create policy team_memberships_select on public.team_memberships for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = team_memberships.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy team_memberships_insert on public.team_memberships for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy team_memberships_update on public.team_memberships for update to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = team_memberships.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check (exists (select 1 from workspace_members where workspace_members.workspace_id = team_memberships.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy team_memberships_delete on public.team_memberships for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = team_memberships.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

-- Owner-controlled sales records. Managers may update or delete any row in the
-- workspace; members may mutate only records assigned to them.
alter table public.accounts enable row level security;
create policy accounts_select on public.accounts for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = accounts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy accounts_insert on public.accounts for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy accounts_update on public.accounts for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = accounts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = accounts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy accounts_delete on public.accounts for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = accounts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.contacts enable row level security;
create policy contacts_select on public.contacts for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy contacts_insert on public.contacts for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy contacts_update on public.contacts for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy contacts_delete on public.contacts for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.leads enable row level security;
create policy leads_select on public.leads for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = leads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy leads_insert on public.leads for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy leads_update on public.leads for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = leads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = leads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy leads_delete on public.leads for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = leads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.opportunities enable row level security;
create policy opportunities_select on public.opportunities for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = opportunities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy opportunities_insert on public.opportunities for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy opportunities_update on public.opportunities for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy opportunities_delete on public.opportunities for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.activities enable row level security;
create policy activities_select on public.activities for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = activities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy activities_insert on public.activities for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy activities_update on public.activities for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy activities_delete on public.activities for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activities.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.tasks enable row level security;
create policy tasks_select on public.tasks for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = tasks.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy tasks_insert on public.tasks for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy tasks_update on public.tasks for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or (exists (select 1 from task_assignees where task_assignees.task_id = tasks.id and task_assignees.user_id = auth.uid()) and exists (select 1 from workspace_members where workspace_members.workspace_id = tasks.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')) or exists (select 1 from workspace_members where workspace_members.workspace_id = tasks.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = tasks.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy tasks_delete on public.tasks for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = tasks.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.notes enable row level security;
create policy notes_select on public.notes for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = notes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy notes_insert on public.notes for insert to authenticated with check (owner_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');
create policy notes_update on public.notes for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = notes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = notes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy notes_delete on public.notes for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = notes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.file_assets enable row level security;
create policy file_assets_select on public.file_assets for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = file_assets.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy file_assets_insert on public.file_assets for insert to authenticated with check (owner_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');
create policy file_assets_update on public.file_assets for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_assets.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_assets.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy file_assets_delete on public.file_assets for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_assets.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.email_threads enable row level security;
create policy email_threads_select on public.email_threads for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = email_threads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy email_threads_insert on public.email_threads for insert to authenticated with check (owner_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');
create policy email_threads_update on public.email_threads for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_threads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_threads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy email_threads_delete on public.email_threads for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_threads.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.campaigns enable row level security;
create policy campaigns_select on public.campaigns for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = campaigns.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy campaigns_insert on public.campaigns for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy campaigns_update on public.campaigns for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaigns.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaigns.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy campaigns_delete on public.campaigns for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaigns.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

alter table public.saved_views enable row level security;
create policy saved_views_select on public.saved_views for select to authenticated using (owner_id = auth.uid() or (is_shared = true and exists (select 1 from workspace_members where workspace_members.workspace_id = saved_views.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')));
create policy saved_views_insert on public.saved_views for insert to authenticated with check (owner_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');
create policy saved_views_update on public.saved_views for update to authenticated using (owner_id = auth.uid()) with check (owner_id = auth.uid());
create policy saved_views_delete on public.saved_views for delete to authenticated using (owner_id = auth.uid());

-- Simple tenant children use created_by ownership for mutations.
alter table public.tags enable row level security;
create policy tags_select on public.tags for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy tags_insert on public.tags for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy tags_update on public.tags for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy tags_delete on public.tags for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

alter table public.pipelines enable row level security;
create policy pipelines_select on public.pipelines for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = pipelines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy pipelines_insert on public.pipelines for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy pipelines_update on public.pipelines for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = pipelines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = pipelines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy pipelines_delete on public.pipelines for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = pipelines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

alter table public.products enable row level security;
create policy products_select on public.products for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = products.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy products_insert on public.products for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy products_update on public.products for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = products.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = products.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy products_delete on public.products for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = products.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

alter table public.price_books enable row level security;
create policy price_books_select on public.price_books for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = price_books.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy price_books_insert on public.price_books for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy price_books_update on public.price_books for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = price_books.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = price_books.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy price_books_delete on public.price_books for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = price_books.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

alter table public.custom_field_definitions enable row level security;
create policy custom_field_definitions_select on public.custom_field_definitions for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_definitions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy custom_field_definitions_insert on public.custom_field_definitions for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy custom_field_definitions_update on public.custom_field_definitions for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_definitions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_definitions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy custom_field_definitions_delete on public.custom_field_definitions for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_definitions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

-- The remaining junction/detail tables inherit tenant visibility by their
-- denormalised workspace_id and bind inserts directly to created_by.
alter table public.account_tags enable row level security;
alter table public.contact_tags enable row level security;
alter table public.pipeline_stages enable row level security;
alter table public.lead_conversions enable row level security;
alter table public.opportunity_contacts enable row level security;
alter table public.opportunity_tags enable row level security;
alter table public.price_book_items enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_lines enable row level security;
alter table public.activity_participants enable row level security;
alter table public.task_assignees enable row level security;
alter table public.file_links enable row level security;
alter table public.email_messages enable row level security;
alter table public.campaign_members enable row level security;
alter table public.custom_field_values enable row level security;
alter table public.notifications enable row level security;
alter table public.audit_events enable row level security;

create policy account_tags_select on public.account_tags for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = account_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy account_tags_insert on public.account_tags for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy account_tags_update on public.account_tags for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = account_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = account_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy account_tags_delete on public.account_tags for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = account_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy contact_tags_select on public.contact_tags for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = contact_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy contact_tags_insert on public.contact_tags for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy contact_tags_update on public.contact_tags for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contact_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contact_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy contact_tags_delete on public.contact_tags for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = contact_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

create policy pipeline_stages_select on public.pipeline_stages for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = pipeline_stages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy pipeline_stages_insert on public.pipeline_stages for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy pipeline_stages_update on public.pipeline_stages for update to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = pipeline_stages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check (exists (select 1 from workspace_members where workspace_members.workspace_id = pipeline_stages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy pipeline_stages_delete on public.pipeline_stages for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = pipeline_stages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy price_book_items_select on public.price_book_items for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = price_book_items.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy price_book_items_insert on public.price_book_items for insert to authenticated with check (created_by = auth.uid() and created_by_role in ('owner','admin') and created_by_status = 'active');
create policy price_book_items_update on public.price_book_items for update to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = price_book_items.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active')) with check (exists (select 1 from workspace_members where workspace_members.workspace_id = price_book_items.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));
create policy price_book_items_delete on public.price_book_items for delete to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = price_book_items.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin') and workspace_members.status = 'active'));

create policy lead_conversions_select on public.lead_conversions for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = lead_conversions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy lead_conversions_insert on public.lead_conversions for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy lead_conversions_update on public.lead_conversions for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = lead_conversions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = lead_conversions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy lead_conversions_delete on public.lead_conversions for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = lead_conversions.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy opportunity_contacts_select on public.opportunity_contacts for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy opportunity_contacts_insert on public.opportunity_contacts for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy opportunity_contacts_update on public.opportunity_contacts for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy opportunity_contacts_delete on public.opportunity_contacts for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_contacts.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy opportunity_tags_select on public.opportunity_tags for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy opportunity_tags_insert on public.opportunity_tags for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy opportunity_tags_update on public.opportunity_tags for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy opportunity_tags_delete on public.opportunity_tags for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = opportunity_tags.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

create policy quotes_select on public.quotes for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = quotes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy quotes_insert on public.quotes for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy quotes_update on public.quotes for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quotes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quotes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy quotes_delete on public.quotes for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quotes.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy email_messages_select on public.email_messages for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = email_messages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy email_messages_insert on public.email_messages for insert to authenticated with check (owner_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');
create policy email_messages_update on public.email_messages for update to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_messages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_messages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy email_messages_delete on public.email_messages for delete to authenticated using ((owner_id = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = email_messages.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

create policy task_assignees_select on public.task_assignees for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy task_assignees_insert on public.task_assignees for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy task_assignees_update on public.task_assignees for update to authenticated using ((user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')) or exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')) or exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy task_assignees_delete on public.task_assignees for delete to authenticated using ((user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')) or exists (select 1 from workspace_members where workspace_members.workspace_id = task_assignees.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));

create policy quote_lines_select on public.quote_lines for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = quote_lines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy quote_lines_insert on public.quote_lines for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy quote_lines_update on public.quote_lines for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quote_lines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quote_lines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy quote_lines_delete on public.quote_lines for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = quote_lines.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy activity_participants_select on public.activity_participants for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = activity_participants.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy activity_participants_insert on public.activity_participants for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy activity_participants_update on public.activity_participants for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activity_participants.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activity_participants.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy activity_participants_delete on public.activity_participants for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = activity_participants.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy file_links_select on public.file_links for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = file_links.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy file_links_insert on public.file_links for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy file_links_update on public.file_links for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_links.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_links.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy file_links_delete on public.file_links for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = file_links.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy campaign_members_select on public.campaign_members for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = campaign_members.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy campaign_members_insert on public.campaign_members for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy campaign_members_update on public.campaign_members for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaign_members.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaign_members.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy campaign_members_delete on public.campaign_members for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = campaign_members.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy custom_field_values_select on public.custom_field_values for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_values.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy custom_field_values_insert on public.custom_field_values for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy custom_field_values_update on public.custom_field_values for update to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_values.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active')) with check ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_values.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy custom_field_values_delete on public.custom_field_values for delete to authenticated using ((created_by = auth.uid() and created_by_status = 'active') or exists (select 1 from workspace_members where workspace_members.workspace_id = custom_field_values.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy notifications_select on public.notifications for select to authenticated using (user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = notifications.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy notifications_insert on public.notifications for insert to authenticated with check (created_by = auth.uid() and created_by_status = 'active');
create policy notifications_update on public.notifications for update to authenticated using (user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = notifications.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active')) with check (user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = notifications.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy notifications_delete on public.notifications for delete to authenticated using (user_id = auth.uid() and exists (select 1 from workspace_members where workspace_members.workspace_id = notifications.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.status = 'active'));
create policy audit_events_select on public.audit_events for select to authenticated using (exists (select 1 from workspace_members where workspace_members.workspace_id = audit_events.workspace_id and workspace_members.user_id = auth.uid() and workspace_members.role in ('owner','admin','manager') and workspace_members.status = 'active'));
create policy audit_events_insert on public.audit_events for insert to authenticated with check (actor_id = auth.uid() and created_by = auth.uid() and created_by_status = 'active');

-- Storage paths use <workspace>/<user>/<entity>/<file>. INSERT avoids a
-- membership subquery by binding the second path component to auth.uid().
create policy crm_files_select on storage.objects for select to authenticated
using (bucket_id = 'crm-files' and owner_id = auth.uid()::text);
create policy crm_files_insert on storage.objects for insert to authenticated
with check (bucket_id = 'crm-files' and owner_id = auth.uid()::text and (storage.foldername(name))[2] = auth.uid()::text);
create policy crm_files_update on storage.objects for update to authenticated
using (bucket_id = 'crm-files' and owner_id = auth.uid()::text)
with check (bucket_id = 'crm-files' and owner_id = auth.uid()::text and (storage.foldername(name))[2] = auth.uid()::text);
create policy crm_files_delete on storage.objects for delete to authenticated
using (bucket_id = 'crm-files' and owner_id = auth.uid()::text);
